CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nickname VARCHAR(255) NOT NULL UNIQUE,
    age INTEGER NOT NULL,
    gender VARCHAR(255) NOT NULL,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password CHAR(60) NOT NULL,
    createdAt DATETIME NOT NULL
) CREATE TABLE IF NOT EXISTS sessions (
    sessionID TEXT PRIMARY KEY,
    userID INTEGER NOT NULL,
    expiresAT TIMESTAMP NOT NULL,
    FOREIGN KEY (userID) REFERENCES users(id),
)